### ISSUE TITLE
`direction` argument example on `placeItem()`

### ISSUE THREAD

**Issue by Ausicius** [Mathrandom7910/moomooapi#6]
Hello, I am pretty new to this whole moomoo.io scripting. I want to have an example argument (direction) for `placeItem()`.
It said numbers, but no matter what I do the placing direction does not change. I would also like to get the example argument for `lookAt()`.

**Comment by a-a-afk** [comment]
[placeItem](https://mathrandom7910.github.io/moomooapi/classes/moomooapi.MooMooAPI.html#placeItem) is a method on the [MooMooAPI](https://mathrandom7910.github.io/moomooapi/classes/moomooapi.MooMooAPI.html) object. It inputs 2 arguments, one being the [ItemId](https://mathrandom7910.github.io/moomooapi/enums/data_objects_items.ItemIds.html) of the item you wish to place, and the second (and optional) direction in radians. If no direction is given (alternatively null) it will place the item in the direction you are currently facing. The `placeItem` method can be used as so (assuming you named your MooMooAPI instance `api`):
`api.placeItem(api.player.currentObject)`
This will place the item you are currently holding. However due to ping and other factors it may produce unwanted results. To place a specific item such as a spike, you can get the spike type a player has (e.g. basic spike, greater spike, spinning, poison) you can use the method [getSpikeType](https://mathrandom7910.github.io/moomooapi/classes/player.SelfPlayer.html#getSpikeType) from the [selfPlayer](https://mathrandom7910.github.io/moomooapi/classes/moomooapi.MooMooAPI.html#player) instance. An example of this would be:
`api.placeItem(api.player.getSpikeType())`

You can use this with direction by declaring the second argument:
Placing a spike to the right of the player:
`api.placeItem(api.player.getSpikeType(), 0)`
Placing a spike above the player:
`api.placeItem(api.player.getSpikeType(), Math.PI / 2)`

[lookAt](https://mathrandom7910.github.io/moomooapi/classes/moomooapi.MooMooAPI.html#lookAt) is a method on the `MooMooAPI` object that sends a packet to "spoof" looking at a certain position. It likely wont be visible without any extra modifications because it does not change the rendered player's rotation. However, it does rotate and can be seen by other players. `lookAt` is mostly just a helper method for aiming at players or buildings. To aim at a player (assuming the variable named `player` is a [Player](https://mathrandom7910.github.io/moomooapi/classes/player.Player.html)) object, one could do something such as:
`api.lookAt(player)`

both of these methods can be used to create a very simple script which places spikes towards a player:
`api.lookAt(player)`
`api.placeItem(api.player.getSpikeType())`

the target player can be found by listening to the [updatePlayer](https://mathrandom7910.github.io/moomooapi/interfaces/events.PlayerEvents.html#updatePlayer) event, such as:
<code>
let player;
api.on("updatePlayer", (playerDat) => {
    if(playerDat.sid != api.player.sid) {
        player = api.getPlayerBySid(playerDat.sid);
    }
});
</code>

Sorry that code highlighting is whack, I have no idea how to do it properly in markdown lol.
While it was made in typescript, I created a [mod](https://github.com/Mathrandom7910/justclientmoo) which uses this api, and is probably the best reference to go off of learning this api.
There are a few examples [here](https://github.com/Mathrandom7910/moomooapi/tree/master/examples) that can also be used for reference.

**Comment by Ausicius** [comment]
It works! Thanks for answering my random silly goofy question 😁
